CREATE TABLE "coverPages" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "coverPages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uid" varchar,
	"institutionName" varchar,
	"title" varchar,
	"subject" varchar,
	"studentName" varchar,
	"indexNumber" varchar,
	"className" varchar,
	"teacherName" varchar,
	"date" varchar,
	"template" varchar,
	"pageSize" varchar,
	"logoUrl" varchar,
	"aiModel" varchar,
	"generationMethod" varchar,
	"originalPrompt" varchar,
	"createdBy" varchar,
	"createdAt" timestamp DEFAULT now()
);
